FROM python:2.7

WORKDIR /share/hormozdiarilab/Codes/NebulousSerendipity/src/python

COPY . /share/hormozdiarilab/Codes/NebulousSerendipity/src/python

ENV PATH="/share/hormozdiarilab/Codes/NebulousSerendipity/src/python:${PATH}"
