all: c_counter.cpp
	/software/gcc/8.2.0/lssc0-linux/bin/g++ -std=c++17 -o c_counter.out c_counter.cpp
debug: c_counter.cpp
	/software/gcc/8.2.0/lssc0-linux/bin/g++ -std=c++11 -g -o c_counter.out c_counter.cpp
