#!/bin/bash
source PWD.sh
source BED.sh
source SIM.sh
DATA="/share/hormozdiarilab/Codes/NebulousSerendipity/data/"
BED_GENOME=$(echo $BED | awk -F. '{ print $1 }')
echo BED_GENOME $BED_GENOME
TARGET_BED="$GEN.$(echo $BED | sed 's|[^.]*\.||')"
echo TARGET_BED $TARGET_BED
LP="../MixIntegerProgrammingJob/"
SIM="../Simulation/"
################################################################################
#cat $SIM"sample.vcf" | grep 'SVTYPE=DEL' | sed 's/\([[:alnum:]]*[[:blank:]]*[[:digit:]]*\).*SVTYPE=DEL;STRANDS=\([+-]*\):.*;END=\([[:digit:]]*\);.*/\1\t\3\t\2/' > $SIM"lumpy.bed"
cat $SIM"svtyper.vcf" | grep 'SVTYPE=DEL' | sed 's/\([[:alnum:]]*[[:blank:]]*[[:digit:]]*\).*;END=\([[:digit:]]*\);[^[:blank:]]*[[:blank:]]*[^[:blank:]]*[[:blank:]]*\([0/1]*\):.*/\1\t\2\t\3/' > $SIM"svtyper.bed"
################################################################################
bedtools intersect -b $SIM"svtyper.bed" -a $LP"merge.bed" -wa -f 0.8 -F 0.8 | sort -u > shared.bed
bedtools intersect -b $SIM"svtyper.bed" -a $LP"absent.bed" -wa -f 0.8 -F 0.8 | sort -u > absent.bed
################################################################################
grep "0/1" $SIM"svtyper.bed" > 10_tmp.bed
grep "1/1" $SIM"svtyper.bed" > 11_tmp.bed
bedtools intersect -b 10_tmp.bed -a $LP"merge.bed" -wa -f 0.8 -F 0.8 | sort -u > 10.bed
bedtools intersect -b 11_tmp.bed -a $LP"merge.bed" -wa -f 0.8 -F 0.8 | sort -u > 11.bed
rm 10_tmp.bed
rm 11_tmp.bed
################################################################################
bedtools intersect -a 11.bed -b $SIM"homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > lumpy_11_as_11.bed
bedtools intersect -a 10.bed -b $SIM"homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > lumpy_11_as_10.bed
bedtools intersect -a 11.bed -b $SIM"heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > lumpy_10_as_11.bed
bedtools intersect -a 10.bed -b $SIM"heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > lumpy_10_as_10.bed
bedtools intersect -a 11.bed -b $SIM"absent.bed" -wa -f 1.0 -F 1.0 | sort -u > lumpy_00_as_11.bed
bedtools intersect -a 10.bed -b $SIM"absent.bed" -wa -f 1.0 -F 1.0 | sort -u > lumpy_00_as_10.bed
bedtools intersect -b shared.bed -a $SIM"homozygous.bed" -wa -f 1.0 -F 1.0 -v | sort -u > lumpy_11_as_00.bed
bedtools intersect -b shared.bed -a $SIM"heterozygous.bed" -wa -f 1.0 -F 1.0 -v | sort -u > lumpy_10_as_00.bed
################################################################################
bedtools intersect -a $LP"00_as_00.bed" -b shared.bed -f 1.0 -F 1.0 | sort -u > nebula_00_as_00.bed
bedtools intersect -a $LP"00_as_10.bed" -b shared.bed -f 1.0 -F 1.0 | sort -u > nebula_00_as_10.bed
bedtools intersect -a $LP"00_as_11.bed" -b shared.bed -f 1.0 -F 1.0 | sort -u > nebula_00_as_11.bed
bedtools intersect -a $LP"10_as_00.bed" -b shared.bed -f 1.0 -F 1.0 | sort -u > nebula_10_as_00.bed
bedtools intersect -a $LP"10_as_10.bed" -b shared.bed -f 1.0 -F 1.0 | sort -u > nebula_10_as_10.bed
bedtools intersect -a $LP"10_as_11.bed" -b shared.bed -f 1.0 -F 1.0 | sort -u > nebula_10_as_11.bed
bedtools intersect -a $LP"11_as_00.bed" -b shared.bed -f 1.0 -F 1.0 | sort -u > nebula_11_as_00.bed
bedtools intersect -a $LP"11_as_10.bed" -b shared.bed -f 1.0 -F 1.0 | sort -u > nebula_11_as_10.bed
bedtools intersect -a $LP"11_as_11.bed" -b shared.bed -f 1.0 -F 1.0 | sort -u > nebula_11_as_11.bed
################################################################################
wc -l *.bed
