#!/bin/bash
source PWD.sh
source BED.sh
source SIM.sh
DATA="/share/hormozdiarilab/Codes/NebulousSerendipity/data/"
BED_GENOME=$(echo $BED | awk -F. "{ print $1 }")
echo $BED_GENOME
TARGET_BED="$GEN.All.$(echo $BED | sed 's|[^.]*\.||')"
echo $TARGET_BED
################################################################################
awk 'BEGIN {FS = "\t"} /^[^(]*\(0, 0\).*/ ' *merge*.bed > 00.bed
awk 'BEGIN {FS = "\t"} /^[^(]*(\(1, 1\)|\(1, 0\)).*/ ' *merge*.bed > present.bed
awk 'BEGIN {FS = "\t"} /^[^(]*\(1, 1\).*/ ' *merge*.bed > 11.bed
awk 'BEGIN {FS = "\t"} /^[^(]*\(1, 0\).*/ ' *merge*.bed > 10.bed
awk 'BEGIN {FS = "\t"} /^.*\(2, 2\).*/ ' *merge*.bed > 22.bed
awk 'BEGIN {FS = "\t"} /^.*\(3, 3\).*/ ' *merge*.bed > 33.bed
awk 'BEGIN {FS = "\t"} /^.*\(4, 4\).*/ ' *merge*.bed > 44.bed
################################################################################
if [ "$SIM" == "--simulation" ]; then
    echo "Simulation"
    SIM="../Simulation/"
    bedtools intersect -a 11.bed -b $SIM"homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_11.bed
    bedtools intersect -a 10.bed -b $SIM"homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_10.bed
    bedtools intersect -a 00.bed -b $SIM"homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_00.bed
    bedtools intersect -a 11.bed -b $SIM"heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_11.bed
    bedtools intersect -a 10.bed -b $SIM"heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_10.bed
    bedtools intersect -a 00.bed -b $SIM"heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_00.bed
    bedtools intersect -a 11.bed -b $SIM"absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_11.bed
    bedtools intersect -a 10.bed -b $SIM"absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_10.bed
    bedtools intersect -a 00.bed -b $SIM"absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_00.bed
    ################################################################################
    cat 11_as_11.bed > true_positive.bed
    cat 11_as_10.bed >> true_positive.bed
    cat 10_as_11.bed >> true_positive.bed
    cat 10_as_10.bed >> true_positive.bed
    cat 00_as_11.bed > false_positive.bed
    cat 00_as_10.bed >> false_positive.bed
    cat 00_as_00.bed > true_negative.bed
    cat 10_as_00.bed > false_negative.bed
    cat 11_as_00.bed >> false_negative.bed
################################################################################
else
    echo $DATA$TARGET_BED
    grep "1|0" $DATA$TARGET_BED > heterozygous.bed
    grep "0|1" $DATA$TARGET_BED >> heterozygous.bed
    grep "1|1" $DATA$TARGET_BED > homozygous.bed
    grep "0|0" $DATA$TARGET_BED > absent.bed
    bedtools intersect -a 11.bed -b "homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_11.bed
    bedtools intersect -a 10.bed -b "homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_10.bed
    bedtools intersect -a 00.bed -b "homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_00.bed
    bedtools intersect -a 11.bed -b "heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_11.bed
    bedtools intersect -a 10.bed -b "heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_10.bed
    bedtools intersect -a 00.bed -b "heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_00.bed
    bedtools intersect -a 11.bed -b "absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_11.bed
    bedtools intersect -a 10.bed -b "absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_10.bed
    bedtools intersect -a 00.bed -b "absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_00.bed
    #
    bedtools intersect -a 00.bed -b $DATA$BED -f 1.0 > false_negative.bed
    sort -n -k2 -o false_negative.bed false_negative.bed

    bedtools intersect -a 00.bed -b $DATA$BED -f 1.0 -v > true_negative.bed
    sort -n -k2 -o true_negative.bed true_negative.bed

    bedtools intersect -a present.bed -b $DATA$BED -f 1.0 > true_positive.bed
    sort -n -k2 -o true_positive.bed true_positive.bed

    bedtools intersect -a present.bed -b $DATA$BED -f 1.0 -v > false_positive.bed
    sort -n -k2 -o false_positive.bed false_positive.bed
fi
wc -l *.bed
