#!/bin/bash
BED=$(pwd | awk -F "/" '{ for(i = 1; i <= NF; i++) { if($i ~ /.*\.bed/) { print $i } } }' | xargs)
echo $BED
BED_GENOME=$(echo $BED | awk -F "." '{print $1}')
echo $BED_GENOME
EVENT=$(pwd | awk -F "/" '{ if ($0 ~ /'.*DEL.*'/) { print "DEL" } else { print "INV" } }' | xargs)
echo $EVENT
REF=$(pwd | awk -F "/" '{ if ($0 ~ /'.*hg19.*'/) { print "hg19" } else { print "hg38" } }' | xargs)
echo $REF
GENOME=$(pwd | awk -F "/" '{ print $(NF - 2)}' | xargs)
echo $GENOME
DATA="/share/hormozdiarilab/Codes/NebulousSerendipity/data/"
TARGET=$GENOME.$REF.$EVENT.bed
echo $TARGET
################################################################################
awk 'BEGIN {FS = "\t"} /^[^(].*\(0, 0\).*/ ' merge.bed > 00.bed
awk 'BEGIN {FS = "\t"} /^[^(]*(\(1, 1\)|\(1, 0\)).*/ ' merge.bed > present.bed
awk 'BEGIN {FS = "\t"} /^[^(].*\(1, 1\).*/ ' merge.bed > 11.bed
awk 'BEGIN {FS = "\t"} /^[^(].*\(1, 0\).*/ ' merge.bed > 10.bed
awk 'BEGIN {FS = "\t"} /^[^(].*\(2, 2\).*/ ' merge.bed > 22.bed
awk 'BEGIN {FS = "\t"} /^[^(].*\(3, 3\).*/ ' merge.bed > 33.bed
awk 'BEGIN {FS = "\t"} /^[^(].*\(4, 4\).*/ ' merge.bed > 44.bed
################################################################################
if [ "$BED_GENOME" == "$GENOME" ]; then
    ################################################################################
    if [[ $GENOME == *"Random"* ]]; then
        echo "Simulation"
        SIM="/share/hormozdiarilab/Codes/NebulousSerendipity/output/$BED/31/Simulation/"
        bedtools intersect -a 11.bed -b $SIM"homozygous.bed" -wa -f 1.0 | sort -u > 11_as_11.bed
        bedtools intersect -a 10.bed -b $SIM"homozygous.bed" -wa -f 1.0 | sort -u > 11_as_10.bed
        bedtools intersect -a 00.bed -b $SIM"homozygous.bed" -wa -f 1.0 | sort -u > 11_as_00.bed
        bedtools intersect -a 11.bed -b $SIM"heterozygous.bed" -wa -f 1.0 | sort -u > 10_as_11.bed
        bedtools intersect -a 10.bed -b $SIM"heterozygous.bed" -wa -f 1.0 | sort -u > 10_as_10.bed
        bedtools intersect -a 00.bed -b $SIM"heterozygous.bed" -wa -f 1.0 | sort -u > 10_as_00.bed
        bedtools intersect -a 11.bed -b $SIM"present.bed" -wa -f 1.0 -v | sort -u > 00_as_11.bed
        bedtools intersect -a 10.bed -b $SIM"present.bed" -wa -f 1.0 -v | sort -u > 00_as_10.bed
        bedtools intersect -a 00.bed -b $SIM"present.bed" -wa -f 1.0 -v | sort -u > 00_as_00.bed
    ################################################################################
    else
        bedtools intersect -a 00.bed -b $DATA$BED -f 1.0 > false_negative.bed
        sort -n -k2 -o false_negative.bed false_negative.bed

        bedtools intersect -a 00.bed -b $DATA$BED -f 1.0 -v > true_negative.bed
        sort -n -k2 -o true_negative.bed true_negative.bed

        bedtools intersect -a present.bed -b $DATA$BED -f 1.0 > true_positive.bed
        sort -n -k2 -o true_positive.bed true_positive.bed

        bedtools intersect -a present.bed -b $DATA$BED -f 1.0 -v > false_positive.bed
        sort -n -k2 -o false_positive.bed false_positive.bed
    ################################################################################
    fi
else
    ################################################################################
    bedtools intersect -a $DATA$BED -b $DATA$TARGET -wa -f 0.9 | sort -u > $DATA$BED"_in_"$TARGET
    bedtools intersect -a $DATA$BED -b $DATA$TARGET -wa -f 0.9 -v | sort -u > $DATA$BED"_not_in_"$TARGET
    bedtools intersect -a $DATA$BED -b $DATA$TARGET -wa -F 0.9 | sort -u > $DATA$BED"_from_"$TARGET
    bedtools intersect -a $DATA$BED -b $DATA$TARGET -wa -F 0.9 -v | sort -u > $DATA$BED"_not_from_"$TARGET
    ################################################################################
    bedtools intersect -a 11.bed -b $DATA$BED"_in_"$TARGET -wa -f 1.0 | sort -u > 11_or_01_as_11.bed
    bedtools intersect -a 10.bed -b $DATA$BED"_in_"$TARGET -wa -f 1.0 | sort -u > 11_or_01_as_10.bed
    bedtools intersect -a 00.bed -b $DATA$BED"_in_"$TARGET -wa -f 1.0 | sort -u > 11_or_01_as_00.bed
    bedtools intersect -a 00.bed -b $DATA$BED"_not_in_"$TARGET -wa -f 1.0 | sort -u > 00_as_00.bed
    bedtools intersect -a 11.bed -b $DATA$BED"_not_in_"$TARGET -wa -f 1.0 | sort -u > 00_as_11.bed
    bedtools intersect -a 10.bed -b $DATA$BED"_not_in_"$TARGET -wa -f 1.0 | sort -u > 00_as_10.bed
    ################################################################################
    cat 11_or_01_as_11.bed > true_positive.bed
    cat 11_or_01_as_10.bed >> true_positive.bed
    cat 11_or_01_as_00.bed > false_negative.bed
    cat 00_as_11.bed > false_positive.bed
    cat 00_as_10.bed >> false_positive.bed
    cat 00_as_00.bed > true_negative.bed
    ################################################################################
fi
wc -l *.bed
