#!/bin/bash
source PWD.sh
source BED.sh
source SIM.sh
DATA="/share/hormozdiarilab/Codes/NebulousSerendipity/data/"
BED_GENOME=$(echo $BED | awk -F. "{ print $1 }")
echo $BED_GENOME
TARGET_BED="$GEN.$(echo $BED | sed 's|[^.]*\.||')"
echo $TARGET_BED
F="merge.bed"
################################################################################
awk 'BEGIN {FS = "\t"} { if ($4 ~ /00/)    { print $0 } }' $F > 00.bed
awk 'BEGIN {FS = "\t"} { if ($4 ~ /11|10/) { print $0 } }' $F > present.bed
awk 'BEGIN {FS = "\t"} { if ($4 ~ /11/)    { print $0 } }' $F > 11.bed
awk 'BEGIN {FS = "\t"} { if ($4 ~ /10/)    { print $0 } }' $F > 10.bed
################################################################################
if [[ "$SIM" =~ ^--simulation ]]; then
    echo "Simulation"
    SIM="../Simulation/"
    bedtools intersect -a 11.bed -b $SIM"homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_11.bed
    bedtools intersect -a 10.bed -b $SIM"homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_10.bed
    bedtools intersect -a 00.bed -b $SIM"homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_00.bed
    bedtools intersect -a 11.bed -b $SIM"heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_11.bed
    bedtools intersect -a 10.bed -b $SIM"heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_10.bed
    bedtools intersect -a 00.bed -b $SIM"heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_00.bed
    bedtools intersect -a 11.bed -b $SIM"absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_11.bed
    bedtools intersect -a 10.bed -b $SIM"absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_10.bed
    bedtools intersect -a 00.bed -b $SIM"absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_00.bed
    ################################################################################
    cat 11_as_11.bed > true_positive.bed
    cat 11_as_10.bed >> true_positive.bed
    cat 10_as_11.bed >> true_positive.bed
    cat 10_as_10.bed >> true_positive.bed
    cat 00_as_11.bed > false_positive.bed
    cat 00_as_10.bed >> false_positive.bed
    cat 00_as_00.bed > true_negative.bed
    cat 10_as_00.bed > false_negative.bed
    cat 11_as_00.bed >> false_negative.bed
################################################################################
else
    echo "Real data"
    echo $DATA$TARGET_BED
    grep "1|0" $DATA$TARGET_BED > heterozygous.bed
    grep "0|1" $DATA$TARGET_BED >> heterozygous.bed
    grep "1|1" $DATA$TARGET_BED > homozygous.bed
    grep "0|0" $DATA$TARGET_BED > absent.bed
    bedtools intersect -a $DATA$BED -b $DATA$TARGET_BED -wa -f 1.0 -F 1.0 -v | sort -u >> absent.bed
    #
    bedtools intersect -a 11.bed -b "homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_11.bed
    bedtools intersect -a 10.bed -b "homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_10.bed
    bedtools intersect -a 00.bed -b "homozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 11_as_00.bed
    bedtools intersect -a 11.bed -b "heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_11.bed
    bedtools intersect -a 10.bed -b "heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_10.bed
    bedtools intersect -a 00.bed -b "heterozygous.bed" -wa -f 1.0 -F 1.0 | sort -u > 10_as_00.bed
    bedtools intersect -a 11.bed -b "absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_11.bed
    bedtools intersect -a 10.bed -b "absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_10.bed
    bedtools intersect -a 00.bed -b "absent.bed" -wa -f 1.0 -F 1.0 | sort -u > 00_as_00.bed
    #
    bedtools intersect -a 00.bed -b $DATA$TARGET_BED -f 1.0 -F 1.0 > false_negative.bed
    sort -n -k2 -o false_negative.bed false_negative.bed

    bedtools intersect -a 00.bed -b $DATA$TARGET_BED -f 1.0 -F 1.0 -v > true_negative.bed
    sort -n -k2 -o true_negative.bed true_negative.bed

    bedtools intersect -a present.bed -b $DATA$TARGET_BED -f 1.0 -F 1.0 > true_positive.bed
    sort -n -k2 -o true_positive.bed true_positive.bed

    bedtools intersect -a present.bed -b $DATA$TARGET_BED -f 1.0 -F 1.0 -v > false_positive.bed
    sort -n -k2 -o false_positive.bed false_positive.bed
fi
wc -l *.bed
